### ISSUE TITLE
Possible to run mergerfs as a docker container ?

### ISSUE THREAD

**Issue by Cyriltra** [trapexit/mergerfs#703] opened 2020-01-31 09:38 UTC
Hello,

I was wondering if it's possible to run mergerfs within a container to merge host folders (which are also volumes to other containers) ?
Right now I have some containers, but have mergerfs directly on the host. I would like to dockerize everything so I can easily orchestrate everything after reboot.

Thank you

**Comment by trapexit** [comment] 2020-01-31 11:02
Sure. You just have to set it up correctly. Pass in /dev/fuse and probably run as "privileged" if you're using Docker.

**Comment by trapexit** [comment] 2020-01-31 11:03
But realize that for supplemental groups it will be looking that up in the container which means if you are trying to use host groups as supplemental in the containers it won't work.

**Comment by Cyriltra** [comment] 2020-01-31 11:42
Hi,

not sure to understand what your second comments means, I'll have to expand my knowledge on that :D
Regarding the docker, which one should i use ?
https://hub.docker.com/r/trapexit/mergerfs-build-env or mergerfs-static-build ?

Thank you

**Comment by trapexit** [comment] 2020-01-31 11:54
Supplemental groups are secondary user groups a user (uid) can belong to. The user ids and group ids in every container may or may not be shared with the host but the supplemental groups are picked up on a typical machine through the file /etc/group which will be different between containers and the host. So if mergerfs runs on the host then it will cache the host's /etc/group. If in a container... there.

As for an image... I don't have one that is for runtime. Most people install it on the host as they want to share among all their containers. It however is easy enough to build... but I don't know how familiar you are with building images.

**Comment by Cyriltra** [comment] 2020-01-31 11:56
ok i understand, i will check it up, otherwise I will keep using mergerfs outside docker.
Thanks a lot for your support !

**Comment by trapexit** [comment] 2020-01-31 11:59
I've been meaning to create an image but it wasn't clear if anyone wanted the extra hassle.

If I have the time this weekend I can look into it.

**Comment by Cyriltra** [comment] 2020-01-31 12:27
that would be nice :)
I will also check it on my side, but I'm far from being an expert...

**Comment by rubicon** [comment] 2020-02-17 09:15
I’d love to have a container. That would be great. I’m hoping to point my Sonarr, Radar, and maybe other containers to use the volumes in a mergerfs container.

**Comment by trapexit** [comment] 2020-02-17 15:27
You can build a container now with any of the packages. The problem is how you deploy it. If you want to use shared supplemental groups you'll need to manage that manually. You'll also need to manage proper permissions and mounting in of the fuse device. Most people find it more hassle than it's worth.

**Comment by hotio** [comment] 2020-03-13 16:31
@Cyriltra @rubicon just letting you guys know that I've created a container `hotio/mergerfs`

@trapexit is there a particular reason that `mergerfs --version` seems to exit with 1 by default, eventhough the command seems to produce no errors?

```
mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```

**Comment by trapexit** [comment] 2020-03-13 16:33
I think it's a behavior of libfuse. sshfs does the same thing. I can change it.

**Comment by hotio** [comment] 2020-03-13 16:36
I'm using it to test if mergerfs atleast starts in my build pipeline, so if it were to exit with 0 unless something actually was wrong that would be great...

**Comment by trapexit** [comment] 2020-03-13 17:35
Sure. I'll put in something for the next release.

**Comment by Cyriltra** [comment] 2020-03-14 12:15
> @Cyriltra @rubicon just letting you guys know that I've created a container `hotio/mergerfs`
> 
> @trapexit is there a particular reason that `mergerfs --version` seems to exit with 1 by default, eventhough the command seems to produce no errors?
> 
> ```
> mergerfs version: 2.29.0
> FUSE library version: 2.9.7-mergerfs_2.29.0
> fusermount version: 2.9.7-mergerfs_2.29.0
> using FUSE kernel interface version 7.31
> ```

Thank @hotio , I will give it a try

**Comment by olvier** [comment] 2020-07-09 18:59
hey folks,
hey @hotio, 

i'm totally in love with docker and so i want to use mergerfs in docker, too :)

now i am stuck with an error `fuse: missing mountpoint parameter`

i added container with following parameters:

`sudo docker run \
	--name=hotio-mergerfs-cli \
	--env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
	--env=BRANCHES=/source1:/source2 \
	--env=MOUNTPOINT=/mounts/MergerFS \
	--env=TZ=Europe/Berlin \
	--volume=/volume1/docker/mergerfs/config:/config \
	--volume=/volume2/Video2/mergerfs/test1:/source1 \
	--volume=/volume2/Video2/mergerfs/test2:/source2 \
	--volume=/volume2/Video2/mergerfs/movies:/mounts/MergerFS:shared \
	--cap-add SYS_ADMIN \
	--network=bridge \
	--privileged \
	--restart=no \
	--device /dev/fuse \
	--label org.label-schema.build-date="2020-06-06T10:11:32Z" \
	--label org.label-schema.vcs-ref="8090586b1a7a" \
	--label maintainer="hotio" \
	--label org.label-schema.vcs-url="https://github.com/hotio/docker-mergerfs.git" \
	--label org.label-schema.schema-version="1.0" \
	--log-driver=db \
	--detach=true \
    	--security-opt apparmor:unconfined \
	hotio/mergerfs:latest`

does somebody see my problem? and also has a solution for it?

**Comment by sprat** [comment] 2021-07-07 17:43
I am starting using linuxkit, and so a mergerfs docker/OCI image is a use-case for me. It's possible to share the mergerfs mountpoint with other containers, and even with the host by using special options in the mount/bind statement of the docker container.

**Comment by trapexit** [comment] 2021-07-07 18:08
Gonna close this. Not sure I'll build an "official" image given hotio seems to have that covered. I can look at it again later should it be relevant.

**Closed** 2021-07-07 18:08 UTC
Labels: enhancement, question

**Comment by dannymichel** [comment] 2022-09-11 22:44
> hey folks, hey @hotio,
> 
> i'm totally in love with docker and so i want to use mergerfs in docker, too :)
> 
> now i am stuck with an error `fuse: missing mountpoint parameter`
> 
> i added container with following parameters:
> 
> `sudo docker run \ --name=hotio-mergerfs-cli \ --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \ --env=BRANCHES=/source1:/source2 \ --env=MOUNTPOINT=/mounts/MergerFS \ --env=TZ=Europe/Berlin \ --volume=/volume1/docker/mergerfs/config:/config \ --volume=/volume2/Video2/mergerfs/test1:/source1 \ --volume=/volume2/Video2/mergerfs/test2:/source2 \ --volume=/volume2/Video2/mergerfs/movies:/mounts/MergerFS:shared \ --cap-add SYS_ADMIN \ --network=bridge \ --privileged \ --restart=no \ --device /dev/fuse \ --label org.label-schema.build-date="2020-06-06T10:11:32Z" \ --label org.label-schema.vcs-ref="8090586b1a7a" \ --label maintainer="hotio" \ --label org.label-schema.vcs-url="https://github.com/hotio/docker-mergerfs.git" \ --label org.label-schema.schema-version="1.0" \ --log-driver=db \ --detach=true \ --security-opt apparmor:unconfined \ hotio/mergerfs:latest`
> 
> does somebody see my problem? and also has a solution for it?
> 
> ![image](https://user-images.githubusercontent.com/13106409/87080068-57c0fd00-c227-11ea-849a-9263665b6122.png)

he just took his container down

**Comment by mrhotio** [comment] 2022-09-11 23:58
Yes I did.

**Comment by dannymichel** [comment] 2022-09-12 01:49
> Yes I did.

Why if I may ask.

**Comment by mrhotio** [comment] 2022-09-12 05:16
I explained my reasoning in my discord server....

**Comment by dannymichel** [comment] 2022-09-12 05:26
> I explained my reasoning in my discord server....

I don't see where this discord server is linked.
