### ISSUE TITLE
Add recommended samba settings to docs

### ISSUE THREAD

**Issue by da-mkay** [trapexit/mergerfs#560] opened 2019-01-16 17:35 UTC
General description
===================
I'm wondering which samba settings work best with mergerfs.
Since probably many people use samba together with mergerfs it would be nice to have recommended options listed here.

Expected behavior
=================
When I write to my mergerfs-mount directly I get around 80-90 MiB/s.
When I write through samba to the mergerfs-mount I should get similar speeds, since the gigabit LAN is not the limiting factor (should handle 90 MiB/s very well).

Actual behavior
===============
However, writing to the mergerfs-mount through a samba share I get speed that frequently changes between 90 MiB/s and 20 MiB/s, going up and down all the time, the average may be 60 MiB/s.

What samba/mergerfs options are best used together to get stable transfer-speed in the 80-90 MiB/s range?

System information
==================

* Ubuntu 18.04
* mergerfs version: 2.21.0
* FUSE library version: 2.9.7
* fusermount version: 2.9.7
* using FUSE kernel interface version 7.19
* mergerfs options: defaults,allow_other,direct_io,use_ino,minfreespace=0,func.getattr=newest,category.create=mfs
* Linux NAS 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Samba Version 4.7.6-Ubuntu
* Drives use ext4, formatted using "-T huge"

**Comment by trapexit** [comment] 2019-01-16 17:54
There aren't any settings to recommend. Performance can vary for many reasons and regarding mergerfs the kernel, underlying storage, etc. can all impact performance. Many use Samba without issue. You'd need to do more investigation to see what the issue may be.

Have you read the performance section of the docs and tried the suggestions?

**Comment by trapexit** [comment] 2019-01-23 03:52
I'm going to close this. If you can provide examples or suggestions as to what you think should be in the docs please post them but otherwise I'm unsure what you're looking for.

**Closed by trapexit** 2019-01-23 03:52 UTC

**Comment by da-mkay** [comment] 2019-01-28 17:57
Hi and sorry for the late reply. I did some further investigation, because the settings mentioned in docs (even the performance section) didn't change anything for me. However, I now have full speed over 1-Gbit LAN (Samba, Windows 10 client) 👍 . I will share my new setup here for the case anyone else has the same problems.

My previous setup was the following 🐌 :

- multiple HDDs, each having one partition encrypted with LUKS (options: -c aes-xts-plain64 -s 512 --align-payload 512)
- ext4 on the encrypted volumes (options: -m 0.3 -T huge)
- mergerfs on top of those ext4 filesystems
- shared mergerfs filesystem over smbd
- write files from Windows 10 to samba share

But then I got the mentioned problems:

- heavily varying transfer speed, usually between 20 and 90 MiB/s (average 60 MiB/s), regularly dropping down to 0 MiB/s
- copying of files was often delayed some seconds

So I did dome testing: I tried changing the options of all affected parties, even tried the default options: LUKS, ext4, mergerfs, smbd. However, the problems persisted. Sometimes, a little improvement was noticeable, sometimes not. 
Then I started to remove one part after another from the equation: LUKS, mergerfs, smbd, etc.. 
After removing LUKS I got fullspeed (ext4, mergerfs, smbd). OK, I readded LUKS but removed smbd: I also got fullspeed (copying files directly using dd) etc..
But honestly, neither was an option. But then I remembered, that before using mergerfs, I used mdadm together with XFS, not ext4. So, I switched to XFS and the problems were gone 🎉 .

So my new setup is 🚀 :

- multiple HDDs, each having one partition encrypted with LUKS (options: -c aes-xts-plain64 -s 512)
- XFS on the encrypted volumes (default options)
- mergerfs on top of XFS filesystems (basically default options: defaults,allow_other,direct_io,use_ino,func.getattr=newest,category.create=mfs)
- shared mergerfs filesystem over smbd (no special settings applied, Ubuntu's defaults)

Using this setup I got immediate transfers (no delay) combined with almost constant speed when copying from Windows 10, no drops down to 0 MiB/s.
OK, I didn't get fullspeed at that time, just 70-80 MiB/s.
However, I then replaced the CPU with a slightly faster one and now I get constant 100 MiB/s (Well, HDDs get slower when they are getting full, but that's OK 😛 ).

Now you might say, that the faster CPU alone could have solved the problems. Nope 😁  I restored my previous setup and I were back to heavily varying speed combined with drops and delayed transfers, even with the new CPU installed.

So it looks to me like there are some incompatibilities when using LUKS + ext4 + mergerfs + smbd. Removing one of them often improves or solves the problems, but using all together leads to problems. At least for the two (almost hardware identical) systems that I manage.

**Comment by trapexit** [comment] 2019-01-28 18:32
Curious. Thanks for the write up. I can include a comment in the docs about this. Perhaps someone could dig further and find out the cause.
