### ISSUE TITLE
OMV5 not surviving first reboot, problem with mergefs and luks

### ISSUE THREAD

**Issue by Kasperx** [trapexit/mergerfs#909] opened 2021-05-22 17:46 UTC
Hi

I started a discussion in forum for os omv 4 and got into problems with mergefs, luks and boot, as seen in topic.
Here is the link to previous thread: https://forum.openmediavault.org/index.php?thread/37268-omv5-not-surviving-first-reboot/

I don't understand why this doesn't work or I found a litte bug. Somepne there wrote this is a problem in debian and mergefs.
Thank you in advance.

**Comment by trapexit** [comment] 2021-05-22 17:51
Why do you think this is a problem with mergerfs?

**Comment by Kasperx** [comment] 2021-05-23 16:55
Thank you for answering.
Did you read the other "original" post?

Btw: Its omv 5.

Because debian 10, running on my computer, doesn't boot with mergefs entry in `/etc/fstag` enabled (not commented = deactivated), even with `no-fail` flag inserted (done by default by openmediavault 5). All other entries, that "reference" devices, don't harm the system on user console (I don't know whats effected in system beyond users eyes), even if they can't be mounted at boot as well because of luks partition.

Makes me wonder why the entry for mergefs (activated) runs into problems on boot. As someone answered in other post there might be a problem in mergefs program.
So here I am.

**Comment by trapexit** [comment] 2021-05-23 17:38
There aren't any real details to the threads. As I read it it is simply that branches or mount points don't exist when mounted which if true is like any filesystem ever. You can't mount something that doesn't exist. Provide me with explicit details as requested in the docs and ticket template and I can comment further.

**Comment by trapexit** [comment] 2021-05-27 21:54
I'm going to close this as no details have been provided specific to mergerfs that indicate there is a problem. As I read the claims it sounds like the branch directories or the mount directory does not exist at the time mergerfs is called and therefore fails as any other filesystem would. If the target path doesn't exist mergerfs has nothing to do with the decision to fail.

**Closed by trapexit** 2021-05-27 21:55 UTC
Labels: investigating, question

**Comment by Kasperx** [comment] 2021-05-30 18:23
Sorry, took a longer time to answer.
I don't have debug messanges or something like that. All I have is the other post with all answers from omv people and the system problem.
Btw I was linked to here by one of the users, so might be a deeper problem with this program.
In my point of view its all described there. More details are the mergefs program itself, so this forum.

> directory does not exist at the time mergerfs is called and therefore fails as any other filesystem would

Well, yes, but why does the main system =debian crash on mergefs "fail"? (Do you need a screenshot? Its off now)

**Comment by trapexit** [comment] 2021-05-30 20:56
>I don't have debug messanges or something like that. All I have is the other post with all answers from omv people and the system problem.

If I don't have real info on the situation it really isn't possible for me to comment. There is just vague comments about stuff I don't use and don't have experience with. 

>Well, yes, but why does the main system =debian crash on mergefs "fail"? (Do you need a screenshot? Its off now)

Bootup will halt any time a filesystem fails to mount or you have errors in your fstab. "nofail" is a feature of the mount tool. Not the OS. Not all implementations of mount (the tool) support "nofail". The libfuse tooling doesn't understand nofail. I can't change that. I can try to replace the entire tooling of the libfuse userspace and mimic what the mount tool does but that's it. It won't help with any other libfuse based filesystem.

**Comment by trapexit** [comment] 2021-05-30 21:46
I'm not going to argue that "nofail" isn't convenient but the reality is that it's not a universal feature and mergerfs is not unique here. mergerfs itself doesn't have control here. Likely it has no control over the situation you are referring to. Whether certain options are valid or if the target mount point exists is managed by libfuse tooling. Same as sshfs and many other filesystems. The only thing possible, as I mentioned, is to replace the standard tooling and rewrite it.

**Comment by Kasperx** [comment] 2021-05-31 20:14
Thank you for details and motivation.

> Bootup will halt any time a filesystem fails to mount or you have errors in your fstab. "nofail" is a feature of the mount tool. Not the OS.

Why doesn't debian care for all other devices that also require luks decrypt. The problem is "just" on mergefs device(s).

So in my understanding it sounds like the combination with mergefs / (libfuse) / luks (cryptsetup) / debian (10) is not compatible. :(
Yes it's a bit more than an experiment and unusual. But it's in openmediavault 5 and a possible and maybe easy way to activate, close to "official" system.
Found a bug there?

**Comment by trapexit** [comment] 2021-05-31 20:42
>Why doesn't debian care for all other devices that also require luks decrypt. The problem is "just" on mergefs device(s).

Such as? Provide me with actual details and settings. You have yet to provide a single example and I can't keep arguing about something that I can't even understand let alone reproduce. Nothing you've presented sounds like a bug. It sounds like the same thing that would happen with **every** other filesystem that was misconfigured.

**Comment by trapexit** [comment] 2021-05-31 20:51
The order of mounting matters. If OMV doesn't allow you to use systemd dependencies to manage that's not mergerfs' issue. It is a OMV plugin issue. 

If a mount path doesn't exist when mergerfs is asked to mount there is nothing that can be done. The target path must exist for mounting to work. It won't even get to mergerfs mounting if it doesn't exist.

If the source branch paths don't exist then that's fine. mergerfs doesn't care. If you use branch globbing then of course you'd run into problems because again... if the source doesn't exist then globbing can't find it.

**Comment by Kasperx** [comment] 2021-05-31 21:22
Tanks, sounds logical.
I'm gonna give you pics & examples tomorrow.

**Comment by Kasperx** [comment] 2021-06-01 20:27
Here some screenshots
I think I need to apologize. If my eyes don't trick me all lines are marked with `nofail` except the one for `mergefs`.

![IMG_20210601_214119#](https://user-images.githubusercontent.com/10506030/120385118-4e50ef80-c327-11eb-992f-903b71822f7b.jpg)
As you see its the last line.
![IMG_20210601_214730#](https://user-images.githubusercontent.com/10506030/120385953-5198ab00-c328-11eb-9e68-d5a70cb9969f.jpg)

**Comment by trapexit** [comment] 2021-06-01 21:10
I'm sorry but this isn't useful. You have to tell me what is happening. There has to be some log somewhere. Is the target location available at the time mergerfs is mounted? Something. Anything that would indicate what the error is?
