### ISSUE TITLE
Directory move fails

### ISSUE THREAD

**Issue by abattech** [trapexit/mergerfs#307] opened 2016-08-28 15:11 UTC
/s is the mount point of the pool.

**/s/incoming> sudo mv ../backup_ /s/incoming**
mv: inter-device move failed: ‘../backup_’ to ‘/s/incoming/backup_’;
unable to remove target: Is a directory

**Background info:**
Everything is ext4
mergerfs version: 2.14.0-18-gf0f8e52
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19

**Comment by trapexit** [comment] 2016-08-28 15:38
What settings? What policies? Have you read the details in the documents regarding rename?

https://github.com/trapexit/mergerfs#rename--link

**Comment by abattech** [comment] 2016-08-28 15:40
fstab entry:
fstab entry: /mnt/server2/pool/d* /s fuse.mergerfs category.create=epmfs,defaults,allow_other,minfreespace=50G,fsname=merged_storage,direct_io 0 0

**Comment by abattech** [comment] 2016-08-28 15:43
Yes, i have read the rename details, but i cannot parse them sufficiently to make sense of the failure i am describing. Sorry for causing trouble if this is trivial.

All other settings (beyond fstab params i listed above) are default.

**Comment by trapexit** [comment] 2016-08-28 15:49
Just as with #308 there isn't enough information for me to comment. I need literally every piece of information about the files, directories, and drives. I need to be able to reproduce it.

**Comment by abattech** [comment] 2016-08-28 16:10
drwxrwxr-x 3 abat abat 4096 Aug 26 22:09 /mnt/server2/pool/d001/incoming
drwxrwxr-x 3 abat abat 4096 Aug 26 22:50 /mnt/server2/pool/d002/incoming
drwxrwxr-x 4 abat abat 4096 Aug 27 23:37 /mnt/server2/pool/d003/incoming

/dev/sdg1       3.7T  3.6T   56G  99% /mnt/server2/pool/d001
/dev/sda1       3.7T  3.6T   19G 100% /mnt/server2/pool/d002
/dev/sdd1       3.7T  3.6T   50G  99% /mnt/server2/pool/d003

There are a few other disks in the pool, all empty, rw by me.

abat is me.


The directory backup_ i am trying to move is under /mnt/server2/pool/d003/incoming.

**Comment by abattech** [comment] 2016-08-28 16:18
BTW, I think you could easily create a tool for users to automatically collect all required information about setting,s FS and drives.

**Comment by trapexit** [comment] 2016-08-28 17:03
Yes, I could. However, in the past most of the bug reports are false positives and have been addressed via documentation. There are tools offered which help audit mergerfs mounts for inconsistent permissions and duplicated files which tends to lead to the most problems for people.

**Comment by trapexit** [comment] 2016-08-28 17:06
The mounts aren't sufficient for me to determine why it's happening. 

'mv' is a complex operation. It tries to call `rename` and then falls back to copying files and then deleting the old ones. That translates to several filesystem calls per directory or file. Each one can experience issues depending on several factors. Permissions, which drives they are on, what policy you use, etc.

Almost certainly if you changed to `mfs` your issue would disappear because `epmfs` follows the complex logic as laid out in the documentation.

**Comment by trapexit** [comment] 2016-10-19 16:54
I'm closing this for now. If you can provide me with a simple reproduction I'll look into it again.

**Closed by trapexit** 2016-10-19 16:54 UTC
