### ISSUE TITLE
Multiple Mergerfs Pools

### ISSUE THREAD

**Issue by clayboyx** [trapexit/mergerfs#507] opened 2018-10-02 05:06 UTC
General description
===================
i have 3 pools 
my drives are mounted at /mnt/data/disk,1,2,3,4,5,6 etc
i created 3 merfs
 w/ /mnt/disk 1,3,5 /mnt/storage 1
w/ /mnt/disk 2,4,6 /mnt/storage 2
w/ /mnt/disk 1,2,3,4,5,6 /mnt/storage 3

that my fstab layout
fuse.mergerfs defaults,allow_other,nonempty,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=200G,fsname=mergerfsPoo$
 
Expected behavior
=================

when i send data to storage 2 the data is written storage 2 with minfreespace=200G

Actual behavior
===============
when i send data to storage 2 the data is written to storage 3 for some reason ... what am i doing wrong

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V` 2.24.2
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ ] Linux version: `uname -a` Ubunutu 18.04.1
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h` ext 4 -8TB Reds
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment] 2018-10-02 12:17
I don't understand what you're asking. If you're creating 3 separate mounts with the 3rd one having the same as 1 and 2 then you'd obviously see the same files in 2 on 3.

**Comment by clayboyx** [comment] 2018-10-02 15:13
ok hopefully i can explain this better.... 
ok so i have my drives mounted in /mnt/data/drive 1-13
i want to create 1 pool with all drives in a "erofs"readonly mode mounted at /storage
2nd pool  eplfs minfreespace=20g moveonenospc with drives 1,3,5 mounted at /storage 1
3rd pool  eplfs minfreespace=20g moveonenospc with drives 2,4,6 mounted at /storage 2
i did that and it works fine until i try to write data to /storage 1  but the data ends up going to drives on /storage 2 instead.

so is that happening because i have a pool with all drives mounted  or is there a way to set it up so the data goes to the proper drives will still having a pool up for read only purpose with all drives in the pool?

**Comment by trapexit** [comment] 2018-10-02 15:29
Also... why would you use erofs when you can simply mount with "ro" and have it actually read-only?

**Comment by trapexit** [comment] 2018-10-02 16:37
To set readonly you'd do what you do on any mount... set `ro` option.

I'm assuming the "movies" one is cut off? Regardless... nothing looks out of place but that doesn't mean this is where the problem is. If you use symlinks or bind mounts etc it could cross drives. All you have to do is look at mergerfs' runtime settings and you can see all possible path targets. If it's not in the srcmounts list its not a possible location.

**Comment by clayboyx** [comment] 2018-10-02 16:40
all that went over my head... just an fyi i'm a linux noob ... how would i apply the  ro  option 

ex: 
mnt/data/* /mnt/disks fuse.mergerfs defaults,allow_other,nonempty,use_ino,ro,fsname=mergerfsPoolDisks 0 0

like that or no?  apologies if i'm asking simple questions still new to this whole setup.

**Comment by trapexit** [comment] 2018-10-02 16:43
Yes. It's a standard mount option. Check the man pages for more.

**Comment by clayboyx** [comment] 2018-10-02 16:43
ok so that example is correct... ill be looking more thru the manual

**Comment by clayboyx** [comment] 2018-10-02 16:54
can you show me and example of how you would setup a read only mount? i'm setting it up so i can plug it into Grafana to read data.. from the manual i understand readonly and r/w drives can be mixed...

**Comment by trapexit** [comment] 2018-10-02 16:58
What do you mean? Just above you provided an example of a read only mount as I explained how to do it.

**Comment by clayboyx** [comment] 2018-10-02 17:04
ok cool seemed like theirs more that can be added like the symlink etc ... i'll read more before i ask more questions  thanks for your patience

**Comment by trapexit** [comment] 2018-10-20 22:53
Any update?

**Comment by clayboyx** [comment] 2018-10-20 23:01
Working beautifully thanks man I've tested reading data haven't tested
writing yet also got a pool setup over NFS

**Comment by trapexit** [comment] 2018-10-20 23:12
Is this still a problem? Did you figure it out? I'd like to close this ticket if its no longer needed.

**Comment by clayboyx** [comment] 2018-10-20 23:14
Can be closed working

**Closed** 2018-10-20 23:15 UTC
