### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by qweasdzxc787** [trapexit/mergerfs#443] opened 2017-10-14 21:16 UTC
Having some trouble with mergerfs. A bit of context:

Linux, Fedora 26
I have 14 8TB data drives, all mounted at /export/Archive_01 through /export/Archive_14

2 mergerfs mounts:
/storage 
Mounted with /export/Archive_* to aggregate all of the drives. create policy mfs.

/fill 
Mounted with all the drives minus Archive_14, which is my currently filling drive where all new files are downloaded to. (I only have 01-13 as snapraid data drives to keep the parity from changing all the time. Files only ever get removed from 01-13 with this setup, so if I lose one of these drives, I won't lose anything, only restore something that was deleted since the last sync).

Attached is the current df --o output and tune2fs outputs for all the drives. I have plenty of inodes, and zero reserved space. ~250GB free per drive, shouldn't be an issue. Additionally, I can create directories and create files on all the drives individually, so this is an issue with mergerfs.

I use an rsync command to move files from /export/Archive_14 to /fill:
sudo ionice -c3 rsync -Ahal --remove-source-files --progress --log-file=/home/server/rsync_media_fill_`date +%Y%m%d%H%M%S`.txt --preallocate --inplace --exclude='**.part'"

Attached is /etc/fstab, df output, and tune2fs outputs for all the drives.

When running the rsync command, I get the following output:
rsync: open "/fill/TV/file.mp4" failed: No space left on device (28)

[df.txt](https://github.com/trapexit/mergerfs/files/1385009/df.txt)

[tune2fs.txt](https://github.com/trapexit/mergerfs/files/1385010/tune2fs.txt)
 
[fstab.txt](https://github.com/trapexit/mergerfs/files/1385011/fstab.txt)

**Comment by qweasdzxc787** [comment] 2017-10-14 21:33
I thought perhaps lazytime mount option might have something to do with the so I removed it from fstab, still getting failures with just defaults,relatime for all the drives.

**Comment by qweasdzxc787** [comment] 2017-10-14 21:45
It seems it is particular files that trigger this behavior, I have a specific file that won't write to /fill with mv, cp, or rsync. The only extended attribute is extents for the file. Nothing unusual.

**Comment by trapexit** [comment] 2017-10-14 22:28
This doesn't happen when you try to cp a file from Archive_14 to any single drive?

**Comment by qweasdzxc787** [comment] 2017-10-14 22:43
Correct, no issue at all.

**Comment by trapexit** [comment] 2017-10-14 22:59
mergerfs doesn't ever return no space. You'll need to strace cp, rsync and/or mergerfs to see what it's trying to do.

**Comment by qweasdzxc787** [comment] 2017-10-17 23:48
Here's what's happening inside of rsync. Re-running the rsync command sent the file it skipped the first time:

 

`lstat("Documents/audio/file.mp3", {st_mode=S_IFREG|0644, st_size=864003508, ...}) = 0

getpid()                                = 102000

stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3585, ...}) = 0

write(3, "2017/10/17 18:10:44 [102000] ERR"..., 112) = 112

write(2, "ERROR: Skipping sender remove fo"..., 82ERROR: Skipping sender remove for changed file: Documents/audio/file.mp3) = 82

write(2, "\n", 1

)                       = 1`

 

Error 112 is EHOSTDOWN I believe.

**Comment by trapexit** [comment] 2017-10-18 00:16
What's returning error 112? The write isn't. That's how much it wrote.

**Comment by trapexit** [comment] 2017-10-18 00:16
Can you attach the trace?

**Comment by qweasdzxc787** [comment] 2017-10-18 02:31
[strace.zip](https://github.com/trapexit/mergerfs/files/1393244/strace.zip)

**Comment by qweasdzxc787** [comment] 2017-10-18 02:32
It's big...

**Comment by qweasdzxc787** [comment] 2017-10-18 21:15
Any insight into why this is happening? Generally I can rerun the rsync command and it works properly, and worst case scenario I can mv the file directly to one of the drives, but it's a general nuisance.

**Comment by trapexit** [comment] 2017-10-18 21:27
Where is this no space error? I don't see any such errors in the trace.

Please make the most concise and simple reproduction of this.

You've not given me enough information to comment.

**Comment by qweasdzxc787** [comment] 2017-10-21 20:57
Ok, finally saw the issue again. Single file copy to /fill/ fails. cp strace and mergerfs trace attached.
[cp_trace.txt](https://github.com/trapexit/mergerfs/files/1404439/cp_trace.txt)
[mergerfs.trace.txt](https://github.com/trapexit/mergerfs/files/1404440/mergerfs.trace.txt)

**Comment by qweasdzxc787** [comment] 2017-10-21 21:50
All the drives mounted to /fill have at least 133 GB free.

**Comment by trapexit** [comment] 2017-10-22 04:07
What filesystem is on /export/Archive_05?

The filesystem is returning ENOSPC when attempting to copy metadata.

```
3742  open("/export/Archive_05/...", O_RDONLY|O_NONBLOCK) = 4
3742  ioctl(4, FS_IOC_SETFLAGS, 0x7f22bc7ef0bc) = -1 ENOSPC (No space left on device)
3742  close(4)                          = 0
```

**Comment by qweasdzxc787** [comment] 2017-10-22 04:22
All drives are ext4

**Comment by trapexit** [comment] 2017-10-22 04:41
Can you try using `chattr` on that path? 

`sudo chattr +i "/export/Archive_05/TV/Korean/The Return of Superman"`

This is effectively what mergerfs is doing and it's returning the no space error. This works fine on my system and most every user I know who uses ext4. I'm unaware of any reason that it should be returning ENOSPC.

**Comment by qweasdzxc787** [comment] 2017-10-22 04:53
No help. It seems this issue is specific the Archive_05. It occurs when it's the drive with the most free space, rsync functions normally otherwise. Tried both setting and clearing the immutable flag on that directory, no change.

**Comment by qweasdzxc787** [comment] 2017-10-22 04:55
FYI, I can still copy files directly to Archive_05 without issue.

**Comment by trapexit** [comment] 2017-10-22 05:09
I doubt rsync or cp do what mergerfs does. It's more thorough and tries to copy file attributes. Mergerfs is just returning the error it receives from the system. If chattr on that same directory  under the same user (root) doesn't also result in an error I can't explain it. It's exactly the same code. Without the ability to reproduce this or have access to the problem I don't see what I can do further. I can't find anyone online having a similar issue or what that error would mean in that context.

Can you post a strace of the above chattr?

**Comment by qweasdzxc787** [comment] 2017-10-22 05:16
[strace_chattr.txt](https://github.com/trapexit/mergerfs/files/1404623/strace_chattr.txt)

**Comment by trapexit** [comment] 2017-10-22 14:26
I'm at a complete loss. The traces show the identical behavior except that the OS returns an error when mergerfs trys to set the value.

Can you share more detail on the FS? `tune2fs -l /dev/[archive_05 drive]`

**Comment by qweasdzxc787** [comment] 2017-10-22 15:34
[sdd1_tune2fs.txt](https://github.com/trapexit/mergerfs/files/1405029/sdd1_tune2fs.txt)
[fsattr.txt](https://github.com/trapexit/mergerfs/files/1405030/fsattr.txt)

**Comment by trapexit** [comment] 2017-10-22 17:47
I really don't know. Outside removing the copying of attrs from mergerfs I don't know what can be done since I don't understand why the filesystem is returning that error.

**Comment by qweasdzxc787** [comment] 2017-10-22 18:27
Could you provide a debug build of mergerfs so we can investigate further?

**Comment by trapexit** [comment] 2017-10-22 19:24
What do you mean by debug build? I really don't have any further ideas on debugging this outside reading ext4 kernel code. MergerFS is making the identical call to chattr. AFAIK it shouldn't even be returning ENOSPC and I've found nothing online.

**Comment by qweasdzxc787** [comment] 2017-10-22 19:35
Should we contact Theodore Tso (ext4 maintainer) to report the issue? My running kernel is Linux server 4.13.5-200.fc26.x86_64 #1 SMP Thu Oct 5 16:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by trapexit** [comment] 2017-10-22 19:45
I'd first like to reproduce the issue considering no one else has this problem. Create a clean environment (in a VM or at least with loopback filesystems) and recreate the problem so I can take a look at a live system rather than what we've done above.

**Comment by qweasdzxc787** [comment] 2017-10-22 19:47
I will create a virtualbox VM and try to set it up the same way.

**Comment by Nottt** [comment] 2017-10-25 00:41
`Couldn't delete: remove /path/redacted/ : no space left on device`

I'm seeing this too when my disks are nearly full and I try to delete stuff.

**Comment by trapexit** [comment] 2017-10-25 01:10
Please provide actionable information. What FS, what command did you run, how full, specifics please.

**Comment by Nottt** [comment] 2017-10-25 01:25
@trapexit 

```
df -h
Filesystem                           Size  Used Avail Use% Mounted on
udev                                  32G     0   32G   0% /dev
tmpfs                                6.3G   39M  6.3G   1% /run
/dev/md2                             459G  394G   42G  91% /
tmpfs                                 32G     0   32G   0% /dev/shm
tmpfs                                5.0M     0  5.0M   0% /run/lock
tmpfs                                 32G     0   32G   0% /sys/fs/cgroup
1:2:3                                2.5T  2.4T  111G  96% /home/automation/downloads

`/mnt/disk* /home/automation/downloads/ fuse.mergerfs defaults,allow_other,use_ino,dropcacheonclose=true,moveonenospc=true,minfreespace=10G,ignorepponrename=true,category.create=epmfs  0 0` on my fstab.

I have rutorrent downloading into it, and a rclone move trying to delete the files.

**Comment by trapexit** [comment] 2017-10-25 02:18
What's 'rm' do?

**Comment by Nottt** [comment] 2017-10-26 08:10
Sorry cant help debug it further, as it seems it started working after some time ( maybe because it deleted some stuff smaller than the "space" left ). 

I noticed a few .fusehidden files or similar, but then just removed then manually... If I spot this again I'll try to debug it better ( I should be getting nearly max full disk a lot )

**Comment by trapexit** [comment] 2017-10-26 10:29
.fuse_hidden_* files are indications that something still has files open. It shouldn't be a problem generally that they exist. They will disappear once the file is no longer in use. If you really don't want them around then use the `hard_remove` option.

**Comment by qweasdzxc787** [comment] 2017-11-02 03:30
Modified your mergerfs.balance tool to do what I wanted instead after it completely refused to move files to the mergerfs mount /fill. Script attached. It would be nice if you could add it to your repo. The changes are quite simple, maybe roll it a different mode of mergerfs.balance?
[mergerfs.fill.txt](https://github.com/trapexit/mergerfs/files/1436392/mergerfs.fill.txt)

**Comment by qweasdzxc787** [comment] 2017-11-02 03:31
So I run it on /storage, my main mount. It moves files from the drive with the most free space (my "scratch" drive), to the drive with the second most free space (one of the filling drives that are monitored by snapraid).

**Comment by woolmonkey** [comment] 2017-11-05 13:20
I think I am having the same issue. Every so often a file is being written to the pool and I get out of space error. Try it once or twice more and it works.

**Comment by trapexit** [comment] 2017-11-05 15:44
@woolmonkey That behavior is not what's described above. The claim above is that every time it happens. Given how mergerfs works having an out of space error and then not is not surprising given data is not contiguous. Depending on your settings that's perfectly legit.

Unless someone can precisely show a problem I'm going to have to close this ticket. If people need me to write a "How to submit support questions" document we can get useful reports then I'll do so but so far the reports are unspecific and unproducible.

**Comment by woolmonkey** [comment] 2017-11-05 15:58
Even with 2 TB and more left on each drive?  This is done by a program since I don't usually interface with the drives myself. Your right though it might be something else I'll have to look at somethings somemore.

**Comment by trapexit** [comment] 2017-11-05 16:43
> Even with 2 TB and more left on each drive? 

You didn't say that before.

Again, if you fail to provide useful information to debug the situation I can not help. mergerfs doesn't just randomly return no space errors. If a file can't be written to or created it returns whatever the OS returns. The **only** situation where that's different is if **moveonenospc** is enabled and even then if it was triggered it means that the OS said the filesystem was out of space and the move behavior kicks in which can also result in an error being returned if the move failed.

**Closed** 2017-11-25 19:56 UTC
