### ISSUE TITLE
Getting Transport endpoint is not connected on 2.22.0

### ISSUE THREAD

**Issue by mayoko185** [trapexit/mergerfs#417] opened 2017-06-17 17:34 UTC
Hi first of all thank you for all your work on mergerfs! 

Issue is Im still getting random crashes on the new server I built and df is showing an error "Transport endpoint is not connected" 

Originally I had 2.21 installed and installed libfuse 2.9.7 per the help document and everything worked fine for a while then I suddenly started getting the transport endpoint error again. I checked and saw 2.20 was available, I installed 2.20 but still getting the error.

Not sure if the following will be helpful but ill include it just in case:

running Ubuntu 16.04.2 w/  4.11.3-041103-generic x86_64 mainline kernel (I have to run at least 4.10 since I'm using a ryzen CPU). I've tried the latest available 4.11.6 and still the same issue, I went back to 4.11.3 as that was the last kernel I remember running before I started having the issue again, but still getting it.

found the following in /var/log/kern.log:
Jun 17 13:02:05 sisko kernel: [  738.358947] mergerfs[3076]: segfault at 0 ip 00007fe746e5eb96 sp 00007fe744896168 error 4 in libc-2.23.so[7fe746dd4000+1bf000]

When I do mergerfs -v I get:
mergerfs version: 2.22.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

**Comment by trapexit** [comment] 2017-06-17 21:24
While there certainly could be something in mergerfs I would suspect the hardware or kernel. A user had random segfaults and after replacing a RAM chip it stopped. Another replaced their CPU and it stopped.

Only thing I can suggest is trying to build mergerfs with debugging symbols (just build it from source but don't strip the binary, it should be a few megabytes in size rather than a few hundred KB) and make sure core dumps are enabled and reproduce the issue. Hopefully it'll core dump and then I can investigate the dump.

**Comment by awong728** [comment] 2017-06-24 13:42
I wanted to report that I'm having the same issue (and same error in the kern.log)
I've been able to reproduce it by transferring a large amount of data over samba.

OS: Ubuntu 16.04.2 LTS, kernel 4.4.0-81
mergerfs version: 2.22.0
FUSE library version: 2.9.7
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

**Comment by trapexit** [comment] 2017-06-24 14:51
Does it also crash with 2.21.0?

**Comment by mayoko185** [comment] 2017-06-24 16:56
Sorry for the late reply, Im honestly not sure how to build something from source, Im still learning (my home server is kinda a pet project) but when I get some free time later ill do some googling and see if I can figure it out.

I did however figure out the trigger, in my case it was the torrent client. I recently added a torrent with a lot of peers and it looks like it was the multiple connections (read/writes?) that was crashing it. I moved my download directory to a drive outside the mergerfs pool and its been smooth sailing since.

**Comment by awong728** [comment] 2017-06-24 17:11
@trapexit Yes, it still crashes with 2.21.0.
I'm not sure if my isuse is related to mayoko185's, but I might have traced it to an issue of free space (I'm no developer here, but this is my guess). I'm using epmfs and trying to copy a single 48GB file over. All of the possible existing paths point towards hard drives which are mostly full (< 20GB free space). I would assume that mergerfs would create a folder on another disk in the pool to put that file in, but I don't see that folder.

**Comment by trapexit** [comment] 2017-06-24 17:23
https://github.com/trapexit/mergerfs#building

Unfortunately this is pretty difficult for me to help with if I can't reproduce it. I'll try to setup a separate instance and run some tests.

As for moving of files.... do you have `moveonenospc` enabled? Regardless it shouldn't crash. Let me test that behavior.

**Comment by trapexit** [comment] 2017-06-24 17:33
BTW... to enable core files 

before running mergerfs call `ulimit -c unlimited`

https://stackoverflow.com/questions/6152232/how-to-generate-core-dump-file-in-ubuntu/18428730

**Comment by awong728** [comment] 2017-06-24 17:57
@trapexit Yes. I have moveonenospc=true
I wasn't sure what you meant by building it from source with the debugging, but I've attached the core dump here. Hopefully it'll help.
[_usr_bin_mergerfs.0.zip](https://github.com/trapexit/mergerfs/files/1099921/_usr_bin_mergerfs.0.zip)
p.s. its super awesome that you respond so quick =)

**Comment by trapexit** [comment] 2017-06-24 19:19
I was able to trigger a crash after fooling with things. I'll see what's going on.

**Closed** 2017-06-24 21:04 UTC

**Comment by trapexit** [comment] 2017-06-24 21:28
New release is forthcoming.
