### ISSUE TITLE
Can't create symlinks on the mergerfs drive

### ISSUE THREAD

**Issue by 07416** [trapexit/mergerfs#1022] opened 2022-03-15 14:44 UTC
**Describe the bug**
I can't create a symbolic link using `ln -s` on the merged path. Affects both files and directories.

**To Reproduce**
attempt to symlink a file:
`ln -s /mnt/media/big-buck-bunny.mp4 ~/big-buck-bunny-480p-30s.mp4`

a folder:
`ln -s /mnt/media/big-buck-bunny/ /mnt/media/big-buck-bunny-480p-30s`

Both return `ln: failed to create symbolic link '<path>': Input/output error` and a copy is created instead.

**Expected behavior**

A symlink is successfully created like on a standard volume.

**System information:**

 - OS, kernel version: `uname -a` 
  
`Linux localhost.localdomain 5.16.13-200.fc35.x86_64 #1 SMP PREEMPT Tue Mar 8 22:50:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Fedora 35

- mergerfs version: `mergerfs -V` - 2.33.3
 - mergerfs settings 
 
`mergerfs ': sudo mergerfs -o allow_other,follow-symlinks=all,use_ino,cache.files=partial,dropcacheonclose=true,moveonenospc=true,category.create=mfs /mnt/media1:/mnt/media2 /mnt/media`

 - List of drives, filesystems, & sizes:
   - `df -h`

```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs            14G  6.0M   14G   1% /dev/shm
tmpfs           5.5G  1.9M  5.5G   1% /run
/dev/dm-0       930G  899G   31G  97% /
tmpfs            14G  144K   14G   1% /tmp
/dev/dm-0       930G  899G   31G  97% /home
/dev/nvme0n1p2  976M  289M  621M  32% /boot
/dev/nvme0n1p1  599M   14M  585M   3% /boot/efi
/dev/sda1        11T  8.6T  2.3T  80% /mnt/media2
/dev/sdb1        11T   11T  116G  99% /mnt/media1
tmpfs           2.8G  948K  2.8G   1% /run/user/1000
1:2              22T   20T  2.4T  90% /mnt/media
```

   - `lsblk -f`

```
NAME                                          FSTYPE      FSVER LABEL                 UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sda                                                                                                                                       
└─sda1                                        ext4        1.0   backup2               b3d8b2b3-7e6e-4d93-88c6-a165831dfa7f    2.2T    79% /mnt/media2
sdb                                                                                                                                       
└─sdb1                                        ext4        1.0   backup                ddf5aef3-1fe6-44ed-824d-0ec34eefae60  115.3G    99% /mnt/media1
sdc                                                                                                                                       
sr0                                                                                                                                       
zram0                                                                                                                                     [SWAP]
nvme0n1                                                                                                                                   
├─nvme0n1p1                                   vfat        FAT32                       6BD8-E3BB                               585M     2% /boot/efi
├─nvme0n1p2                                   ext4        1.0                         e0a48589-07ab-45c6-8da2-6cec93ddb54b  620.3M    30% /boot
└─nvme0n1p3                                   crypto_LUKS 2                           bbc10cbf-98d7-4d72-8868-18daf4f27c6d                
  └─luks-bbc10cbf-98d7-4d72-8868-18daf4f27c6d btrfs             fedora_localhost-live 3b846c95-4d48-4e60-9ba6-875e45eec5e0   30.3G    97% /home
                                                                                                                                          /
```

 - A strace of the application having a problem: 
   - `strace -fvTtt -s 256 -o /tmp/app.strace.txt <cmd>`
   - `strace -fvTtt -s 256 -o /tmp/app.strace.txt -p <appPID>`
 - strace of mergerfs while app tried to do it's thing:
   - `strace -fvTtt -s 256 -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

[I'll provide when needed, I haven't yet cleared private data]

**Additional context**

I can create symlinks from `/mnt/media` to my OS drive (or presumably any other).

**Comment by trapexit** [comment] 2022-03-16 13:24
It's not a copy. You've enabled follow-symlinks so the symlink you created shows up as the thing that was linked to. The problem is that I reworked how symlinks worked a while back and forgot to address this situation. It tells the kernel that the file created (the symlink) isn't... because it follows the symlink to whatever you linked to. The kernel doesn't like asking for a symlink and getting something else. I'll try to fix this this week. If you don't need follow-symlinks though you can just not enable it and things will work fine.

**Comment by trapexit** [comment] 2022-03-19 18:24
BTW... curious about your use of follow-symlink. What's the usecase? It was created for a specific situation that I think the user ended up doing something different anyway but I continued with the feature anyway.

**Comment by 07416** [comment] 2022-03-21 12:53
> BTW... curious about your use of follow-symlink. What's the usecase? It was created for a specific situation that I think the user ended up doing something different anyway but I continued with the feature anyway.

Transmission (3.00 `bb6b5a062e`) doesn't appear to be able to follow the paths otherwise.

**Comment by trapexit** [comment] 2022-03-21 12:54
Follow what paths?

**Comment by trapexit** [comment] 2022-03-21 13:16
follow-symlinks has to fundamentally change the behavior of the software. That's why you ran into an issue. It's a new feature that certainly will have edge cases that aren't yet accounted for.

What were the symlinks exactly? mergerfs just reports them like anything else. It's the OS and the software itself that is responsible for resolving them.

There is no reason I can think of that mergerfs should interfere with how transmission uses symlinks. I'd much rather investigate that than you use follow-symlink which impacts the whole pool.

**Comment by 07416** [comment] 2022-03-21 13:38
I'll try again with the "follow-symlinks" option removed and will add some free software torrents (the current ones contain private information). It seems that I also should read the documentation carefully, I blindly assumed that symlinks will flat-out not work without the said flag.

**Comment by trapexit** [comment] 2022-03-21 13:46
symlinks are handled just fine normally. It's just another file type. The point of the feature is to internally resolve symlinks. Similar to a feature in Samba. The original usecase was a person who wanted to pool the targets of symlinks which normally isn't possible.

**Comment by trapexit** [comment] 2022-03-22 19:10
https://github.com/trapexit/mergerfs/releases/tag/2.33.4

If you still need the follow-symlink fix

**Closed by trapexit** 2022-03-22 19:10 UTC
Labels: bug, investigating

**Comment by 07416** [comment] 2022-03-22 22:13
No issues with Transmission, presumed as a user error.

**Comment by trapexit** [comment] 2022-03-23 11:34
OK. While the error might have been a red herring for you there was a real bug there. I'll close this for now. Feel free to reopen if something comes up.
