### ISSUE TITLE
System freezes when writing to mergerfs directory

### ISSUE THREAD

**Issue by Wing-ka-king** [trapexit/mergerfs#1198] opened 2023-06-13 11:55 UTC
**Describe the bug**

I have merged 3 `ext4` formatted 8TB SSD disks into a `mergerfs` union, but any read-write operation on the destination hangs up the whole system and only way out is a hard reboot.

I am using the latest release of mergerfs - 2.35.1-focal

**To Reproduce**

Even a simple command like, `echo "test" > /offload/test.txt` freezes the system. 
Creating and removing folders with `mkdir`,`rm` works alright.

**Expected behavior**

Read-write operations should be executed as normal without hanging up the system.

**System information:**

 - OS, kernel version: `uname -a`
 `Linux CASEPC05 5.15.0-72-generic #79~20.04.1-Ubuntu SMP Thu Apr 20 22:12:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
 - mergerfs version: `mergerfs -V`
 `mergerfs version: 2.35.1`
 - Info about disks:
```
lsblk -f
NAME        FSTYPE   LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0       squashfs                                                  0   100% /snap/bare/5
loop1       squashfs                                                  0   100% /snap/core20/1828
loop2       squashfs                                                  0   100% /snap/gnome-3-38-2004/119
loop3       squashfs                                                  0   100% /snap/snapd/18357
loop4       squashfs                                                  0   100% /snap/snap-store/638
loop5       squashfs                                                  0   100% /snap/gtk-common-themes/1535
sda                                                                            
└─sda1      ext4           8a9cfeda-4b0a-46a0-81c7-c31787ed5ef5    6,9T     0% /mnt/disk1
sdb                                                                            
└─sdb1      ext4           0ba60a2b-24d4-47fe-a58a-1228921e0696    6,9T     0% /mnt/disk2
sdc                                                                            
└─sdc1      ext4           8dd2a07d-e0d9-42e1-a39b-8da24677ac8c    6,9T     0% /mnt/disk3
nvme0n1                                                                        
├─nvme0n1p1 vfat           DECA-4A7E                               946M     1% /boot/efi
└─nvme0n1p2 ext4           7d4c05c6-dcb1-43fd-889e-5a9f9d5216f4  871,3G     2% /

```

 - mergerfs properties from `fstab` entry :
```
/mnt/disk* /offload fuse.mergerfs defaults,cache.files=partial,dropcacheonclose=true,category.create=mfs,nonempty 0 0
```

 - mounted partitions :

```
$ df -H
Filesystem      Size  Used Avail Use% Mounted on
udev             17G     0   17G   0% /dev
tmpfs           3,4G  2,2M  3,4G   1% /run
/dev/nvme0n1p2  1,1T   17G  936G   2% /
tmpfs            17G     0   17G   0% /dev/shm
tmpfs           5,3M  4,1k  5,3M   1% /run/lock
tmpfs            17G     0   17G   0% /sys/fs/cgroup
1:2:3            24T   74k   23T   1% /offload
/dev/loop0      132k  132k     0 100% /snap/bare/5
/dev/loop1       67M   67M     0 100% /snap/core20/1828
/dev/loop2      364M  364M     0 100% /snap/gnome-3-38-2004/119
/dev/loop3       53M   53M     0 100% /snap/snapd/18357
/dev/loop4       49M   49M     0 100% /snap/snap-store/638
/dev/loop5       97M   97M     0 100% /snap/gtk-common-themes/1535
/dev/nvme0n1p1  999M  6,4M  993M   1% /boot/efi
/dev/sda1       8,0T   21k  7,6T   1% /mnt/disk1
/dev/sdb1       8,0T   29k  7,6T   1% /mnt/disk2
/dev/sdc1       8,0T   25k  7,6T   1% /mnt/disk3
tmpfs           3,4G  8,2k  3,4G   1% /run/user/115231894

$ mount | grep offload
1:2:3 on /offload type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)


```
 - strace of mergerfs while app tried to do it's thing:
   - `strace -fvTtt -s 256 -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`¨
   uploaded the file which was written until the system had to be forced shutdown.

[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/11734398/mergerfs.strace.txt)

**Comment by trapexit** [comment] 2023-06-13 12:16
The trace you've provided shows mergerfs running normally and then when attempting to open the file the OS blocks it.

```
415   13:45:56.176996 openat(AT_FDCWD, "/mnt/disk1/test.txt", O_RDONLY|O_LARGEFILE|O_CLOEXEC|0x4000000 <unfinished ...>
```

I'm not able to reproduce this. Can you please make this truly simple as possible. One branch. Try using a tmpfs perhaps.
```
strace -fvTtt -s 256 -o /tmp/mergerfs.strace.txt mergerfs -f -o cache.files=off,category.create=mfs,minfreespace=0 /mnt/disk1 /offload

# in a different terminal
echo "test" > /offload/test.txt
```

**Comment by Wing-ka-king** [comment] 2023-06-14 04:08
Yes, its Ubuntu 20.04.
I first installed using `apt install`, but version 2.28 is available for my distro. Had the same problem with it.
Then I downloaded latest release deb from github and installed with `dpkg -i <path-to-deb>`

**Comment by trapexit** [comment] 2023-06-16 03:12
I really have no idea. Something is perhaps borked with your setup. I created a VM with 20.04.6, installed mergerfs 2.35.1 for Focal AMD64 and it works as expected. You should try using a tmpfs, building mergerfs from scratch or trying a VM yourself on the same hardware.

**Comment by Wing-ka-king** [comment] 2023-06-16 04:41
I tried this on 3 different machines, same result everytime. Deployed with
ansible to minimise differences. But yea, it might be something with my
environment on these machines. Thanks anyways for checking so far.

**Comment by trapexit** [comment] 2023-06-16 04:43
I used 20.04 for years till just this month and had no issue and can't replicate it now with a VM. 

If you can reproduce it in a VM that'd be the best for me as then you could share it.

**Comment by trapexit** [comment] 2023-06-16 11:56
I didn't ask you to close this ticket. I just need something reproducible to be able to debug further.

**Closed** 2023-08-26 23:54 UTC
Labels: bug, investigating
