### ISSUE TITLE
please explain term 'path' in policy descriptions

### ISSUE THREAD

**Issue by markmarz** [trapexit/mergerfs#377] opened 2017-03-09 00:45 UTC
Hi,

Sorry to be so dense, but it's not clear to me what is meant by 'existing path'. For example, in epmfs: "If the path exists on multiple drives use the one with the most free space."

Would you give me an example of what that means? I have 7 data drives in my mergerfs pool, one of which is new. I manually moved some files off 1 of the drives which was at 98.7% of capacity. Still, the new drive has only used about 200 GB out of 6 TB, while the remaining 6 drives are all near their capacity. Although I'm using the epmfs policy, I see when adding new files that the new drive isn't being used.

What is meant by 'existing path'? In my setup, each drive has a Movies directory off the media directory, like this:

`/dev/sdc1: /media/9b6c719a-bd35-46b7-be51-d6082a22329e/Movies`
`/dev/sdf1: /media/988389c5-4273-4879-a5a6-14b3f3a56d33/Movies`
`.... etc`

The mergerfs fstab entry looks like this:
`/media/9482f5d3-6139-4f87-89c7-d1bb7019e005:/media/9b6c719a-bd35-46b7-be51-d6082a22329e:/media/e54c46ce-481f-444a-8000-b3e4f4e9dc08:/media/d2c270c3-a50d-41b0-9b40-d4daeb8e21b4:/media/4518d477-15f4-4892-8e16-ae8c3592fe52:/media/ec260f31-b736-4d71-aa66-333a1937e310:/media/988389c5-4273-4879-a5a6-14b3f3a56d33 /media/7daf8cd3-0f3e-4007-8f8b-269c1bd0b0b4 fuse.mergerfs defaults,allow_other,direct_io,category.create=epmfs,minfreespace=20G 0 0
`

Would the Movies dirs be considered 'existing paths'?

Thanks!
Mark M

**Comment by trapexit** [comment] 2017-03-09 19:33
It means literally the relative paths that exist. Any path preserving policy (ep* policies) only considers drives with the relative path in question.

If you try to create a file in Movies/... all drives with Movies/ are considered for the location.

**Comment by trapexit** [comment] 2017-03-09 19:37
Do you have a suggestion for making the language clearer? "Of all the drives on which the relative path exists, pick the drive with the most free space."?

**Comment by markmarz** [comment] 2017-03-09 19:39
If and when I understand this, I'll be glad to make any clarity suggestions I come up with.

So .. you're saying only the terminal leaf .. in this case 'Movies' .. is considered when testing existence?

Like 'Movies' in:
/media/9b6c719a-bd35-46b7-be51-d6082a22329e/Movies  = exists
/media/9b6c719a-bd35-46b7-be51-d6082a22329e/Whatever/Movies = exists
/media/9b6c719a-bd35-46b7-be51-d6082a22329e/Movies/Whatever = not exists

?

**Comment by trapexit** [comment] 2017-03-09 19:42
I'm saying that you list paths to merge. /mnt/a, /mnt/b, /mnt/c.

From those locations are the relative paths.

If /mnt/a/Movies and /mnt/c/Movies exists... but /mnt/b/Movies does *not* exist then only /mnt/a and /mnt/c are considered when choosing which drive on which to create the file.

**Comment by markmarz** [comment] 2017-03-09 19:46
Okay, I think I'm beginning to get there. 

In my setup, I have 7 data drives. They all have the same relative paths (disregarding mount point) named 'Movies'. Like so:

/media/9b6c719a-bd35-46b7-be51-d6082a22329e/Movies
/media/988389c5-4273-4879-a5a6-14b3f3a56d33/Movies
...

They're all in the mergerfs path. So if I want to add a movie, like 'My Movie (2016'), mergerfs using specified epmfs, will consider all the paths, right?

BUT if I had another path in the mergerfs path, like:
/media/made_up_uuid/NotMovies

.. then mergerfs would not consider this last path as a target for My Movie (2016). Right?

**Comment by trapexit** [comment] 2017-03-09 19:53
I think so... the way you're describing it is weird. It doesn't care what's there (NotMovies)... it cares what's not there. I'm not sure how else to explain it. If the relative path in question does not exist the drive is not considered. 

You have a list of drives `/mnt/a`, `/mnt/b`, `/mnt/c`.

you run `touch /media/mergerfs/Movies/foo`

It scans /mnt/a, /mnt/b, and /mnt/c and filters those that don't have Movies/ and from those left over will sort by free space and then pick the one with the most free space.

**Comment by markmarz** [comment] 2017-03-09 20:07
You're right, I'm explaining it weirdly because I don't understand it. But I think you've penetrated! hah-hah! First off, I think this last example you just gave is an excellent way to explain it. 

I had thought .. mistakenly .. that just adding a Movie dir to the mergerfs pool path would be enough. mergerfs would take care of adding /Movie to any drive he's pooling. I thought that because I didn't consider that there was anything special about a directory compared to a file.

Anyway, somehow I've been rolling along for quite a while and in fact there are Movie dirs hanging off each drive defined in the mergerfs pool. Maybe I added them manually at some point and forgot about it?

Now I've added a new drive. Before I added it to mergerfs, I manually moved some videos onto it, so I could bring those older drives to something less than 98% full. That worked fine. In doing that of course I created a Movie dir in the new drive like this:

/media/988389c5-4273-4879-a5a6-14b3f3a56d33/Movies

.. just like for every other drive. THEN I added /media/988389c5-4273-4879-a5a6-14b3f3a56d33 to mergerfs. He seemed perfectly happy, because I could see the movies I'd moved to the new drive just fine using the mergerfs mount point. So given all that, why is it that when I added a new movie through the pooled mount point, mergerfs chose to put it on some drive other than the newest drive?

**Comment by trapexit** [comment] 2017-03-09 20:15
Do you see the files on that drive in the merged mount? Are you positive the permissions are all correct (given you manually moved the files? If the user making the call to create can't see the path due to permissions it's the same as not there.)

It's extremely difficult to diagnose without *precise* information. All drives, their sizes, free space, all policies, and commands taken. Preferably after reproducing it. These policies calculate behavior on many pieces of information and you have to be sure what that information is relative to the policy and that all the things involved are setup the same.

BTW. If you don't care where files end up then you should change the policy to `mfs` or similar non-path preserving. If you want to distribute files around you can you the mergerfs-tools' mergerfs.balance script. You can check permissions and such with mergerfs.fsck.

**Comment by markmarz** [comment] 2017-03-09 20:30
Every file (including dirs) has correct permissions; I run a shell script to make sure. Forget it, I'll come back to you when I have more time and I see it happening again. I did notice that the file copy was insanely slow. I shutdown the server and restarted this morning and the speed was back to normal, but I didn't pay attention to where the file went.

Regarding the tools, I'd like to use them but I run into xattr module problems. I assume that's a Python module and I know almost nothing about Python.  Like this:

```
root@omv:/media/c32f97f7-2d5a-4dc1-905f-f328799918f4/Work# mergerfs.fsck -h
Traceback (most recent call last):
  File "/usr/local/bin/mergerfs.fsck", line 19, in <module>
    import xattr
ImportError: No module named xattr
root@omv:/media/c32f97f7-2d5a-4dc1-905f-f328799918f4/Work#

```


And this:

`root@omv:/media/c32f97f7-2d5a-4dc1-905f-f328799918f4/Work# mergerfs.dedup -v -d newest /media/9b55d2c2-1cc9-40eb-99dd-f9a8032a0f4c
Traceback (most recent call last):
  File "/usr/local/bin/mergerfs.dedup", line 273, in <module>
    main()
  File "/usr/local/bin/mergerfs.dedup", line 246, in main
    if not ismergerfs(args.dir):
  File "/usr/local/bin/mergerfs.dedup", line 26, in ismergerfs
    os.getxattr(path,"user.mergerfs.fullpath")
AttributeError: 'module' object has no attribute 'getxattr'
root@omv:/media/c32f97f7-2d5a-4dc1-905f-f328799918f4/Work#
`

I realize this is getting off into a tangent, if you'd like me to open an issue re tools installation I will.

**Comment by trapexit** [comment] 2017-03-09 20:31
You need to install `python-xattr`.

**Comment by markmarz** [comment] 2017-03-09 20:33
Tra-la!!

Hah-hah! Thanks! I will now stop bugging you.

**Closed** 2017-03-09 20:38 UTC

**Comment by bugs181** [comment] 2020-05-24 05:48
Had a similar question but did not want to open a new issue if I could avoid it. I'm curious more about clarification than anything. If my understanding is correct, this policy also applies to subdirectories of any depth also.

Example:
```
/mnt/a/Movies/Genre/Action
/mnt/b/Movies/Genre/Comedy
/mnt/c/Movies/Rating/Top10
```

Adding a movie file into the `Genre` subdirectory would only apply to `a` and `b` but not `c`.

How would this work if creating the `Genre` directory in the pool? Does it get created on all drives? Thus, all drives at this point would be considered?

**Comment by trapexit** [comment] 2020-05-24 05:53
>Adding a movie file into the Genre subdirectory would only apply to a and b but not c.

Yes. As the policy description says: "Of all the branches on which the relative path exists..."

The relative base path for a file in Genre is "Movies/Genre". So only branches with "Movies/Genre" are considered.

>How would this work if creating the Genre directory in the pool? 

It depends on the `mkdir` policy. It gets created based on whatever policy you have set.
